title: ACV 2026

# baseurl: "/2026" # the subpath of your site, e.g. /blog
# url: "https://acv-ws.github.io" # the base hostname & protocol for your site, e.g. https://example.com

theme: minima
# theme: jekyll-theme-conference

plugins:
  - jekyll-include-cache




minima:
  nav_pages:
    - about.md
    - portfolio.md

